version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dentaldb
      MYSQL_USER: dentaluser
      MYSQL_PASSWORD: dentalpassword
    ports:
      - "3306:3306"
    networks:
      - dental-network
    volumes:
      - mysql-data:/var/lib/mysql

  receptionist:
    image: dental/receptionist:latest
    container_name: receptionist
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpassword
    networks:
      - dental-network

  patient:
    image: dental/patient:latest
    container_name: patient
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpassword
    networks:
      - dental-network

  doctor:
    image: dental/doctor:latest
    container_name: doctor
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpassword
    networks:
      - dental-network

  appointment:
    image: dental/appointment:latest
    container_name: appointment
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpassword
    networks:
      - dental-network

  apigateway:
    image: dental/apigateway:latest
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - dental-network

  server:
    image: dental/server:latest
    container_name: server
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpassword
    networks:
      - dental-network

  cloudconfig:
    image: dental/cloudconfig:latest
    container_name: cloudconfig
    ports:
      - "8888:8888"
    networks:
      - dental-network

networks:
  dental-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
