eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: doctorservice
          uri: http://localhost:9099
          predicates:
            - Path=/doctors/**
        - id: patientservice
          uri: http://localhost:9098
          predicates:
            - Path=/patient/**

        - id: receptionistservice
          uri: http://localhost:9100
          predicates:
            - Path=/receptionist/**

        - id: appointmentservice
          uri: http://localhost:9101
          predicates:
            - Path=/appointment/**
